version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: Rand0m!
      POSTGRES_USER: root
      POSTGRES_DB: launchpad_booking
    ports:
      - "8001:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pdadmin
    image: dpage/pgadmin4:latest
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Rand0m!
    ports:
      - "8002:80"

  app:
    container_name: app
    build:
      context: .
    restart: on-failure
    ports:
      - "8003:8080"
    tty: true
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data: